---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - group_vars/secrets.yml

  tasks:
    # Mac Preferences: QuickLook, Bluetooth, Color
    # Install mac security updates
    - import_tasks: tasks/mac_pref.yml
      tags: ['prefs']

    # Ensure keys
    - import_tasks: tasks/ids.yml
      tags: ['ids']

    # Git + Git Config
    - import_tasks: tasks/git.yml
      tags: ['git']

    # Vim
    - import_tasks: tasks/vim.yml
      tags: ['vim']

    # Sublime, Atom (plugins ?)
    - name: Ensure Latest Sublime
      homebrew_cask: name=sublime state=latest

    # iTerm

    # zsh + oh-my-zsh + zsh-highligh + zsh-complete + zsh config

    # tmux + tmuxinator (or tmuxp)
    # pyenv 

    # nvm

    # yarn

    # elm elm-format elm-analyze elm-reactor create-elm-app

    # dart + flutter 

    # rbenv (?)
    # jevn + java + maven

    # Unarchiver

    # httpie
    # Postman

    # Spectacle
    - name: Ensure Lates Spectacle 
      homebrew_cask: name=spectacle state=latest
      tags: ['utils']

    # Tunnelblick (import config, start connection)
    - name: Ensure Lastest Tunnelblick
      homebrew_cask: name=tunnelblick state=latest
      tags: ['utils']

    # Chrome + Extentions

    # Firefox, opera, tor, sphere (?)

    
    # VSCode + plugins
    # Xcode
    # Android Studio (+avd, Android File Transfer)
    # Idea CE
    
    # Datagrip
    # Mongo Compass

    # Docker

    # VirtualBox

    # Vargant

    # 1Password
    - name: Install 1Password App
      homebrew_cask: name=1password state=latest
      tags: ['1pass']

    # Dropbox
    # Google Drive (?)

    # Franz
    # Telegram
    # Skype

    # Trello
    # RealTimeBoard
    # VLC

    # Microsoft Remote Desktop
    # Team Viewer

    # Figma
    # Boxy SVG
    # Icon Set Creator

    # Microsoft Office

    # CleanMyMac
    # Parallels Tools

    # Grammarly
    # Torrent

    # WebMoney Keeper
    # Electrum
