---
- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    # essential mac apps
    - import_tasks: tasks/essential_apps.yml
      tags: [essential]

    # firefox, chrome, tor browser
    - import_tasks: tasks/browsers.yml
      tags: [browsers]

    # docker app
    - import_tasks: tasks/docker.yml
      tags: [docker]

    # useful cli tools
    - import_tasks: tasks/cli_tools.yml
      tags: [cli_tools]

    # ssh keys
    - import_tasks: tasks/ids.yml
      tags: [ids]

    # git
    - import_tasks: tasks/git.yml
      tags: [git]

    # iterm + zsh
    - import_tasks: tasks/terminal.yml
      tags: [terminal]

    # neovim
    - import_tasks: tasks/neovim.yml
      tags: [neovim]

    # other mac apps
    - import_tasks: tasks/mac_apps.yml
      tags: [mac_apps]
