---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    timezone: Europe/Moscow
    zshrc_file: "{{ ansible_env.HOME }}/.zshrc"

  tasks:
    # Mac Preferences:  Bluetooth, Color
    - import_tasks: tasks/mac_pref.yml
      tags: [prefs]

    # QuickLook
    - import_tasks: tasks/quick_look.yml
      tags: [qlook]

    # Ensure keys
    - import_tasks: tasks/ids.yml
      tags: [ids]

    # Ensure Git + Git Config
    - import_tasks: tasks/vsc.yml
      tags: [vsc]

    # Vim
    - import_tasks: tasks/editors.yml
      tags: [editors]

    # iterm + zsh + oh-my-zsh + zsh-highlight + zsh-complete + zsh config
    - import_tasks: tasks/terminal.yml
      tags: [terminal]

    # tmux + tmuxinator (or tmuxp)
    - import_tasks: tasks/tmux.yml
      tags: [tmux]

    # pyenv
    - import_tasks: tasks/pyenv.yml
      tags: [pyenv]

    # nvm and yarn
    - import_tasks: tasks/nvm.yml
      tags: [nvm]

    # elm elm-format
    - import_tasks: tasks/elm.yml
      tags: [elm]

    # dart + flutter 
    - import_tasks: tasks/dart.yml
      tags: [dart]

    # rbenv
    - import_tasks: tasks/rbenv.yml
      tags: [rbenv]

    # java + jevn + maven
    - import_tasks: tasks/java.yml
      tags: [java]

    # Some useful cli tools
    - import_tasks: tasks/cli_tools.yml
      tags: [cli_tools]

    # Some useful mac tools
    - import_tasks: tasks/mac_apps.yml
      tags: [mac_apps]

    # Chrome + Extentions, Firefox, Opera, Tor
    - import_tasks: tasks/browsers.yml
      tags: ['browsers']

    # VSCode, Xcode, Android Studio, DataGrip, Mongo Compass
    - import_tasks: tasks/ide.yml
      tags: [ide]

    # Docker
    - import_tasks: tasks/docker.yml
      tags: [docker]

    # VirtualBox + virtualbox extention pack + Vargant
    - import_tasks: tasks/virtualbox.yml
      tags: [virtualbox]
