---
- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    # Fonts
    - import_tasks: tasks/fonts.yml
      tags:
        - font
        - term

    # Terminal
    - import_tasks: tasks/terminal.yml
      tags:
        - term

    # VeraCrypt
    - import_tasks: tasks/veracrypt.yml
      tags:
        - secret

    # Pass
    - import_tasks: tasks/pass.yml
      tags:
        - secret

    # Git
    - import_tasks: tasks/git.yml
      tags: 
        - git

    # Useful cli tools
    - import_tasks: tasks/cli_tools.yml
      tags: 
        - cli_tools

    # Neovim
    - import_tasks: tasks/neovim.yml
      tags: 
        - neovim

    # docker app
    - import_tasks: tasks/docker.yml
      tags: 
        - docker

    # firefox, chrome, tor browser
    - import_tasks: tasks/browsers.yml
      tags: 
        - browsers

    # IDE
    - import_tasks: tasks/ide.yml
      tags:
        - ide

    # LibreOffice
    - import_tasks: tasks/office.yml
      tags: 
        - office

    # Some mac apps
    - import_tasks: tasks/mac_apps.yml
      tags: 
        - mac_apps

    # Upgrade apps
    - import_tasks: tasks/brew_upgrade.yml
      tags:
        - upgrade
