---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    zshrc_file: "{{ home_path }}/.zshrc"

  tasks:
    # Install mac security updates

    # Mac Preferences:  Bluetooth, Color
    - import_tasks: tasks/mac_pref.yml
      tags: ['prefs']

    # QuickLook
    - import_tasks: tasks/quick_look.yml
      tags: [qlook]

    # Ensure keys
    - import_tasks: tasks/ids.yml
      tags: ['ids']

    # Ensure Git + Git Config
    - import_tasks: tasks/vsc.yml
      tags: ['vsc']

    # Vim
    - import_tasks: tasks/editors.yml
      tags: ['editors']

    # iterm + zsh + oh-my-zsh + zsh-highlight + zsh-complete + zsh config
    - import_tasks: tasks/terminal.yml
      tags: ['terminal']

    # tmux + tmuxinator (or tmuxp)
    # pyenv 

    # ffmpeg
    # numpy

    # nvm

    # yarn

    # elm elm-format elm-analyze elm-reactor create-elm-app

    # dart + flutter 

    # rbenv (?)
    # jevn + java + maven

    # Unarchiver

    # httpie
    # Postman

    # Spectacle
    - name: Ensure Lates Spectacle 
      homebrew_cask: name=spectacle state=latest
      tags: ['utils']

    # Tunnelblick (import config, start connection)
    - name: Ensure Lastest Tunnelblick
      homebrew_cask: name=tunnelblick state=latest
      tags: ['utils']

    # Chrome + Extentions

    # Firefox, opera, tor, sphere (?)

    
    # VSCode + plugins
    # Xcode
    # Android Studio (+avd, Android File Transfer)
    # Idea CE
    
    # Datagrip
    # Mongo Compass

    # Docker
    - import_tasks: tasks/docker.yml
      tags: ['docker']

    # VirtualBox

    # Vargant

    # 1Password
    - name: Install 1Password App
      homebrew_cask: name=1password state=latest
      tags: ['1pass']

    # Dropbox
    # Google Drive (?)

    # Franz
    # Telegram
    # Skype

    # Trello
    # RealTimeBoard
    # VLC

    # Microsoft Remote Desktop
    # Team Viewer

    # Figma
    # Boxy SVG
    # Icon Set Creator

    # Microsoft Office

    # CleanMyMac
    # Parallels Tools

    # Grammarly
    # Torrent

    # WebMoney Keeper
    # Electrum
