- block:
  - name: Check 1Password cli
    stat: path={{ binary_path }}/op
    register: op_cli_bin

  - name: Set permissions if binary is already in place
    file: 
      path: "{{ binary_path }}/op"
      state: file
      mode: 0755
    when: op_cli_bin.stat.mode is defined and op_cli_bin.stat.mode != 0755

  - block:
    - name: Remove tmp folder
      file: "path={{ tmp_download_path }} state=absent"

    - name: Create tmp folder
      file: "path={{ tmp_download_path }} state=directory"

    - name: Download 1Password Cli archive
      get_url:
        url: https://cache.agilebits.com/dist/1P/op/pkg/v0.5.5/op_darwin_amd64_v0.5.5.zip
        dest: "{{ tmp_download_path }}/{{ tmp_archive_name }}"
        force: yes

    - name: Unzip
      unarchive:
        src: "{{ tmp_download_path }}/{{ tmp_archive_name }}"
        dest: "{{ tmp_download_path }}" 

    - name: Check op bin
      shell: |
        gpg --receive-keys {{ gpg_key }}
        gpg --verify op.sig op
      args:
        chdir: "{{ tmp_download_path }}"
      
    - name: Move bin to local
      copy:
        src: "{{ tmp_download_path }}/op"
        dest: "{{ binary_path }}"
        mode: 0755

    vars:
      - tmp_download_path: /tmp/1pass
      - tmp_archive_name: op.zip
      - gpg_key: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

    when: not op_cli_bin.stat.exists 
  
  - name: Install jq
    homebrew: name=jq state=latest

  vars:
    - binary_path: /usr/local/bin

