---
- block:
  - name: Ensure Latest Vim
    homebrew: name=vim state=latest

  - name: Ensure cmake (for YouCompeteMe plugin)
    homebrew: name=cmake state=latest

  - name: Ensure vimrc
    copy:
      dest: "{{ home_path }}/.vimrc"
      src: files/vimrc
      remote_src: yes
      force: yes
        
- name: Ensure Latest Sublime
  homebrew_cask: name=sublime-text state=latest

- name: Ensure Latest Atom
  homebrew_cask: name=atom state=latest
