---
- block:
  - name: Ensure Latest Vim
    homebrew: name=vim state=latest

  - name: Ensure cmake (for YouCompeteMe plugin)
    homebrew: name=cmake state=latest

  - name: Ensure vimrc
    copy:
      dest: "{{ ansible_env.HOME }}/.vimrc"
      src: files/vimrc
      remote_src: yes
      force: yes
  
  - name: Ensure vim plugins install
    shell: |
      vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa
      cd {{ ansible_env.HOME }}/.vim/plugged/YouCompleteMe
      ./install.py
        
- name: Ensure Latest Sublime and Atom
  homebrew_cask: 
    name:
      - sublime-text
      - atom
    state: latest
