---
- block:
  - name: Install Latest Vim
    homebrew: name=vim state=latest

  - name: Ensure vimrc
    copy:
      dest: "{{ home_path }}/.vimrc"
      src: files/vimrc
      remote_src: yes
      force: yes

  # TODO: install plugins  
        
- name: Ensure Latest Sublime
  homebrew_cask: name=sublime state=latest

- name: Ensure Latest Atom
  homebrew_cask: name=atom state=latest
