---
- name: Login to 1Password
  shell: echo "{{ op_pass }}" | op signin my.1password.com {{ op_email }} {{ op_secret }} --output=raw
  register: op_token

- block:
  - name: Get ssh keys
    shell: |
      op get document id_rsa > $HOME/.ssh/id_rsa
      op get document id_rsa.pub > $HOME/.ssh/id_rsa.pub
      chmod 600 $HOME/.ssh/id_rsa_new
    
  environment:
    OP_SESSION_my: "{{ op_token.stdout }}"
