---
- name: Load secret info
  include_vars: file=group_vars/secrets.yml
  no_log: yes

- name: Ensure Latest Git
  homebrew: name=git state=latest

- name: Ensure gitconfig
  template: dest={{ ansible_env.HOME }}/.gitconfig src=files/gitconfig.j2
  no_log: yes
