---
###
# This file is almost exact copy of https://github.com/geerlingguy/ansible-role-homebrew/blob/master/tasks/main.yml 
# I've removed some tasks and put all related variables here
# Also I assume that CommandLineTools has been already installed
###
- block:
  - name: Determine Homebrew ownership variables.
    set_fact:
      homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
      homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

  # Homebrew setup prerequisites.
  - name: Ensure Homebrew parent directory has correct permissions.
    file:
      path: "{{ homebrew_prefix }}"
      owner: root
      state: directory
    become: yes

  - name: Ensure Homebrew directory exists.
    file:
      path: "{{ homebrew_install_path }}"
      owner: "{{ homebrew_user }}"
      group: "{{ homebrew_group }}"
      state: directory
      mode: 0775
    become: yes

  # Clone Homebrew.
  - name: Ensure Homebrew is installed.
    git:
      repo: "{{ homebrew_repo }}"
      version: master
      dest: "{{ homebrew_install_path }}"
      update: no
      depth: 1
    become: yes
    become_user: "{{ homebrew_user }}"

  # Adjust Homebrew permissions.
  - block:
    - name: Ensure proper permissions and ownership on homebrew_brew_bin_path dirs.
      file:
        path: "{{ homebrew_brew_bin_path }}"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_group }}"
        mode: 0775

    - name: Ensure proper ownership on homebrew_install_path subdirs.
      file:
        path: "{{ homebrew_install_path }}"
        state: directory
        owner: "{{ homebrew_user }}"
        group: "{{ homebrew_group }}"

    become: yes

  # Place brew binary in proper location and complete setup.
  - name: Check if homebrew binary is already in place.
    stat: "path={{ homebrew_brew_bin_path }}/brew"
    register: homebrew_binary
    check_mode: no

  - name: Symlink brew to homebrew_brew_bin_path.
    file:
      src: "{{ homebrew_install_path }}/bin/brew"
      dest: "{{ homebrew_brew_bin_path }}/brew"
      state: link
    when: not homebrew_binary.stat.exists
    become: yes

  - name: Ensure proper homebrew folders are in place.
    file:
      path: "{{ homebrew_prefix }}/{{ item }}"
      state: directory
      owner: "{{ homebrew_user }}"
      group: "{{ homebrew_group }}"
    become: yes
    loop:
      - Cellar
      - Homebrew
      - Frameworks
      - Caskroom
      - bin
      - etc
      - include
      - lib
      - opt
      - sbin
      - share
      - share/zsh
      - share/zsh/site-functions
      - var

  - block:
    - name: Force update brew after installation.
      command: "{{ homebrew_brew_bin_path }}/brew update --force"
      when: not homebrew_binary.stat.exists

    # Tap.
    - name: Ensure configured taps are tapped.
      homebrew_tap: "tap={{ item }} state=present"
      loop: "{{ homebrew_taps }}"

    # Privilege escalation is only required for inner steps when
    # the `homebrew_user` doesn't match the `ansible_user_id`
    become: "{{ (homebrew_user != ansible_user_id) | bool }}"
    become_user: "{{ homebrew_user }}"
  
  vars:
    homebrew_repo: https://github.com/Homebrew/brew

    homebrew_prefix: /usr/local
    homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
    homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

    homebrew_taps:
      - homebrew/core
      - homebrew/cask
