---
- name: Load secrets info
  include_vars:
    file: group_vars/secrets.yml
  no_log: True

- name: Ensure ssh forlder
  file: dest="{{ ansible_env.HOME }}/.ssh" state=directory

- name: Ensure private key
  copy:
    dest: "{{ keys.private.path }}"
    content: "{{ keys.private.content }}"
    mode: 0600
  no_log: True

- name: Ensure public key
  copy:
    dest: "{{ keys.public.path }}"
    content: "{{ keys.public.content}}"

- name: Ensure ssh config
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    content: "{{ ssh_config }}"
