---
- name: Load secrets info
  include_vars:
    file: group_vars/secrets.yml

- name: Ensure ssh folder
  file:
    dest: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Ensure private key
  copy:
    dest: "{{ keys.private.path }}"
    content: "{{ keys.private.content }}"
    mode: "600"

- name: Ensure public key
  copy:
    dest: "{{ keys.public.path }}"
    content: "{{ keys.public.content}}"
