---
- name: Ensure private key
  copy:
    dest: "{{ keys.private.path }}"
    content: "{{ keys.private.content }}"
    mode: 0600

- name: Ensure public key
  copy:
    dest: "{{ keys.public.path }}"
    content: "{{ keys.public.content}}"
    mode: 0644