---
- name: Ensure caskroom/versions tap
  homebrew_tap: name=caskroom/versions state=present

- name: Ensure java 8 and 9
  homebrew_cask:
    name: [java8, java]
    state: latest

- name: Ensure latest jevn
  homebrew: name=jenv state=latest

# $ jenv add /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
# $ jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home

- name: Ensure latest maven
  homebrew: name=maven state=latest
