---
- name: Install Latest Mac Apps
  homebrew_cask: 
    name: 
      - the-unarchiver
      - postman
      - cleanmymac3
      - parallels-toolbox
      - franz
      - skype
      # - telegram
      - trello
      - vlc
      - remote-desktop-manager-free # Not Microsoft Remote Desktop
      - teamviewer
      - figma
      - microsoft-office
      - grammarly
      - electrum
      # RealTimeBoard
      # Boxy SVG
      # Icon Set Creator
      # Torrent
      # WebMoney Keeper
    state: latest
