---
- block:
    - name: Ensure latest nvm
      homebrew:
        name: nvm
        state: latest

    - name: Ensure nvm base folder
      file:
        path: "{{ nvm_base_dir }}"
        state: directory

    - name: Ensure nvm init file
      copy:
        dest: "{{ zsh_config_path }}/nvm_init"
        content: |
          export NVM_DIR={{ nvm_base_dir }}
          source /usr/local/opt/nvm/nvm.sh

    - name: Ensure source of nvm init file
      lineinfile:
        path: "{{ zshrc_file }}"
        line: source "{{ zsh_config_path }}/nvm_init"

  vars:
    nvm_base_dir: "{{ ansible_env.HOME }}/.local/share/nvm"

- name: Ensure latest yarn
  homebrew:
    name: yarn
    state: latest
