---
- name: Ensure latest nvm
  homebrew:
    name: nvm
    state: latest

- name: Ensure nvm init
  lineinfile: path="{{ zshrc_file }}" line="{{ item }}"
  with_items:
    - export NVM_DIR="$HOME/.nvm"
    - "[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\" # This loads nvm"

- name: Ensure latest yarn
  homebrew:
    name: yarn
    state: latest
    install_options: ignore-dependencies
