---
- name: Ensure quick look plugins
  homebrew_cask: 
    name:
      - qlcolorcode
      - qlimagesize
      - qlmobi
      - qlprettypatch
      - qlstephen
      - qlswift
      - qlvideo
      - quicklook-csv
      - quicklook-json
      - qlcommonmark
      - hetimazipql
      - inloop-qlplayground
      - jupyter-notebook-ql
      - webpquicklook
      - invisorql
      - scriptql
    state: latest
