---
- name: Ensure latest rbenv
  homebrew: name=rbenv state=latest

- name: Ensure latest ruby-build
  homebrew: name=ruby-build state=latest

- name: Ensure rbenv init
  lineinfile:
    path: "{{ zshrc_file }}"
    line: eval "$(rbenv init -)"

- name: Ensure latest ruby version
  shell: |
    eval "$(rbenv init -)"
    rbenv install 2.6.5
    rbenv rehash
    rbenv global 2.6.5
