---
- name: Ensure latest rbenv
  homebrew:
    name: rbenv
    state: latest

- name: Ensure latest ruby-build
  homebrew:
    name: ruby-build
    state: latest

- name: Ensure rbenv init
  lineinfile:
    path: "{{ zshrc_file }}"
    line: eval "$(rbenv init -)"

