---
- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"

- name: Stow custom scripts
  ansible.builtin.import_tasks: stow.yml
  vars:
    stow_package: scripts
    stow_mode: restow
