---
- name: Install Starship
  community.general.homebrew:
    name: starship
    state: latest

- name: Stow starship dotfiles
  ansible.builtin.import_tasks: stow.yml
  vars:
    stow_package: starship
    stow_mode: restow
