---
  - block:
      - name: Ensure iTerm.app
        homebrew_cask:
          name: iterm2
          state: upgraded

      - name: Ensure font tap
        homebrew_tap:
          name: homebrew/cask-fonts
          state: present

      - name: Ensure Jetbrains Font
        homebrew_cask:
          name: font-jetbrains-mono
          state: upgraded

      # TODO: Setup iTerm2 profile: 
      # - set font
      # - allow access to the system clipboard (general -> selection)

    tags: [iterm]

  - block:
      - name: Ensure zsh
        homebrew:
          name: zsh
          state: latest

      - name: Ensure .zshrc file exist
        copy:
          dest: "{{ zshrc_file }}"
          content: ""
          mode: "644"
          force: yes
          backup: yes

      - name: Ensure zsh config folder
        file:
          path: "{{ zsh_config_path }}"
          state: directory

      ### General zsh settings ###

      - name: Ensure general settings
        copy:
          dest: "{{ zsh_config_path }}/general"
          src: files/zsh_general
          remote_src: yes
          force: yes

      - name: Ensure source of general settings file
        lineinfile:
          path: "{{ zshrc_file }}"
          line: source "{{ zsh_config_path }}/general"

      ### Alias ###

      - name: Ensure alias file
        copy:
          dest: "{{ zsh_config_path }}/aliases"
          src: files/zsh_aliases
          remote_src: yes
          force: yes

      - name: Ensure source of alias file
        lineinfile:
          path: "{{ zshrc_file }}"
          line: source "{{ zsh_config_path }}/aliases"

      ### Node Version Manager ###

      - import_tasks: tasks/nvm.yml
        tags: [nvm]

      ### Python Version Manager ###

      - import_tasks: tasks/pyenv.yml
        tags: [pyenv]

      ### Tmux ###

      - import_tasks: tasks/tmux.yml
        tags: [tmux]

      ### Starship ###

      - name: Ensure starship
        homebrew:
          name: starship
          state: latest

      - name: Ensure starship active
        lineinfile:
          path: "{{ zshrc_file }}"
          line: eval "$(starship init zsh)"

      ### Zsh plugin manager ###

      - name: Ensure zplug
        homebrew:
          name: zplug
          state: latest

      - name: Ensure zplug config (list of plugins)
        copy:
          dest: "{{ zsh_config_path }}/zplug"
          src: files/zsh_zplug
          remote_src: yes
          force: yes

      - name: Ensure source of alias file
        lineinfile:
          path: "{{ zshrc_file }}"
          line: source "{{ zsh_config_path }}/zplug"

      - name: Ensure correct permissions
        file:
          path: "{{ item }}"
          mode: "755"
        with_items:
          - /usr/local/share/zsh
          - /usr/local/share/zsh/site-functions

    vars:
      zshrc_file: "{{ ansible_env.HOME }}/.zshrc"
      zsh_config_path: "{{ ansible_env.HOME }}/.config/zsh"

    tags: [zsh]

