---
- name: Install terminal tools
  community.general.homebrew:
    name:
      - stow
      - eza
      - bat
      - jq
      - yq
      - fd
      - ripgrep
      - fzf
      - zoxide
      - mactop
      - tlrc
      - cloc
      - httpie
    state: latest
