---
- block:
    - name: Ensure Latest tmux
      homebrew: name=tmux state=latest

    - name: Ensure plugins directory
      file: dest={{ tmux_plugin_path }} state=directory

    - name: Ensure tmux plugin manager
      git:
        dest: "{{ tmux_plugin_path }}/tpm"
        repo: https://github.com/tmux-plugins/tpm
        force: yes

    - name: Ensure tmux config
      copy:
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        src: files/tmux.conf
        remote_src: yes
        force: yes

    - name: Ensure tmux plugin install
      shell: "source {{ tmux_plugin_path }}/tpm/bin/install_plugins"
      environment:
        TMUX_PLUGIN_MANAGER_PATH: "{{ tmux_plugin_path }}"
      tags: [tmux-plugin]

    - name: Ensure zsh params
      lineinfile: dest={{ zshrc_file }} regexp={{ item.regexp }} line={{ item.line }}
      with_items:
        - { regexp: "^TMUX_PLUGIN_MANAGER_PATH", line: 'TMUX_PLUGIN_MANAGER_PATH={{ tmux_plugin_path }}' }

  vars:
    tmux_plugin_path: "{{ ansible_env.HOME }}/.tmux/plugins"

- block:
    - name: Ensure Latest tmuxinator
      gem: name=tmuxinator state=latest user_install=no
      become: yes

    - name: Ensure tmuxinator config file
      copy:
        dest: "{{ ansible_env.HOME }}/{{ mux_config_file }}"
        src: files/tmuxinator.conf
        remote_src: yes
        force: yes

    - name: Ensure configuration in zshrc
      lineinfile: dest={{ zshrc_file }} line={{ item }}
      with_items:
        - plugins+=(tmux tmuxinator)
        - source ~/{{ mux_config_file }}

    - name: Ensure tmuxinator configs directory
      file: path={{ mux_configs_path }} state=directory

    - name: Ensure tmuxinator configs
      copy:
        dest: "{{ mux_configs_path }}/{{ item }}"
        src: files/tmuxinator/{{ item }}
        remote_src: yes
        force: yes
      with_items:
        - conf.yml

  vars:
    mux_config_file: .tmuxinator.conf
    mux_configs_path: "{{ ansible_env.HOME }}/.config/tmuxinator"
