---
- name: Install zsh completion packages
  community.general.homebrew:
    name:
      - zsh-completions
    state: latest

- name: Stow zsh dotfiles
  ansible.builtin.import_tasks: stow.yml
  vars:
    stow_package: zsh
    stow_mode: restow
